# Generated by Django 5.0.2 on 2024-02-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottletext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('image', models.ImageField(max_length=1000000, upload_to='images/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_unlock', models.DateTimeField()),
            ],
        ),
    ]
