# Generated by Django 5.0.2 on 2024-02-20 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oursweetspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bottletext',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_bottletexts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bottletext',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_bottletexts', to=settings.AUTH_USER_MODEL),
        ),
    ]
