# Generated by Django 5.0.2 on 2024-02-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oursweetspace', '0003_alter_bottletext_image_topic_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottletext',
            name='title',
            field=models.TextField(default='默认标题', max_length=100),
        ),
    ]
